version: '3.9'

services:
  parser_db:
    image: postgres:latest
    container_name: parser_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parser
    ports:
      - "5431:5432"
  
  parser_back:
    image: webapi:latest
    build:
      context: .
      dockerfile: Parser/Dockerfile
    container_name: parser_back
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DefaultConnection: "Host=parser_db;Port=5432;Username=postgres;Password=postgres;Database=parser"
    depends_on:
      - parser_db